title: Jared DiPietro
email: jared135@hotmail.ca
baseurl: "https://imposerr.github.io"
url: "/Jared-DiPietro"


collections:

  illustrations:

    output: true

    permalink: /:collection/:path/

design:
  output: true
  permalink: /:collection/:path/

sass:
  style: compact

